[package]
name = "release-on-merge-action"
authors = ["Dex <dexwritescode@proton.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
regex = "1.9.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
