[package]
name = "release-on-merge-action"
authors = ["Dex"]
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.20" } 
serde =  { version = "1.0", features = ["derive"] }
