[package]
name = "release-on-merge-action"
authors = ["Dex <dexwritescode@proton.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
octocrab = "0.31.0"
regex = "1.9.6"
