name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Test the action in Docker and print the output
    - name: Release on merge action
      id: release
      uses: ./
      with:
        version-increment-strategy: 'patch'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `release` step
    - name: Get the output version
      run: echo "The bumped version is ${{ steps.release.outputs.version }}"
