name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        #args: --release --all-features
    - uses: actions-rs/cargo@v1
      with:
        command: test

    # Test the action in Docker and print the output
    - name: Release on merge action
      id: release
      uses: ./
      with:
        version-increment-strategy: 'patch'
    # Use the output from the `release` step
    - name: Get the output version
      run: echo "The bumped version is ${{ steps.release.outputs.semver }}"
