name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    # Test the action in Docker and print the output
    - name: Release on merge action
      id: release
      uses: ./
      with:
        dry-run: true
    
    # Use the output from the `release` step
    - name: Get the output version  
      run: |
          echo "version ${{ steps.release.outputs.version }}"
          echo "tag ${{ steps.release.outputs.tag }}"
